import { Layout } from '@/components/Layout';
import Head from 'next/head';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import Image from 'next/image';
import { AnimatedText } from '@/components/AnimatedText';
import { HireMe } from '@/components/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import { CustomLink } from '@/components/CustomLink';
import { Education } from '@/components/Education';
import { Experience } from '@/components/Experience';
import { About } from '@/components/About';
import Skills from '@/components/Skills';
import { Button } from '@/components/Button';


export default function Home() {
  return (
    <>
      <Head>
        <title>Software Engineer | Denzel Udemba</title>
        <meta
          name='description'
          content='generated by create next app'
        />
      </Head>
      <main className=' text-colors-dark w-full mb-16 flex flex-col items-center justify-center'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2 '>
              <Image
                src={profilePic}
                alt='Denzel Udemba'
                className='w-full h-auto'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText
                text='Turning Vision Into Reality With Code And Design.'
                className='!text-6xl !text-left'
              />
              <p className='my-4 text-base font-medium dark:text-colors-light/80'>
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Button
                 text="Resume"
                 download={false}
                 href='/resume'
                 target='_blank'
                />
                <CustomLink 
                   title='Contact' 
                  className='ml-4 text-lg font-medium text-colors-dark dark:text-colors-light left-0 -bottom-0.5'
                  href='mailto:abcd@gmail.com'
                  target={'_blank'}
                  >
                  Contact
                </CustomLink >
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image
            src={lightBulb}
            alt='Denzel Udemba'
            className='w-full h-auto'
          />
        </div>
        <About />
        <Skills />
        <Experience />
        <Education />
      </main>
    </>
  );
}
