import { NavBar } from '@/components/NavBar';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='generated by create next app'
        />
      </Head>
      <main>Home</main>
    </>
  );
}
